version: '3.8'

services:
  postgres:
    image: postgres
    container_name: test-golilla-clone
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test-golilla-clone-postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: test-golilla-clone-redis
    restart: no
    ports:
      - "6380:6379"

  node-runner:
    image: node:20
    container_name: test-golilla-clone-node-code-runner
    restart: no
    working_dir: /usr/src/app
    volumes:
      - ./sandbox:/usr/src/app
    command: tail -f /dev/null

volumes:
  postgres_data:
